---
  name: PR
  
  on:
    push:
      branches:
        - '*'
        - '*/*'
        - '**'
        - '!main'

  jobs:    
    pr:
      uses: obervinov/_templates/.github/workflows/pr.yaml@v2.1.0

    terraform:
      uses: obervinov/_templates/.github/workflows/terraform.yaml@v2.1.0
