---
  name: Release
  
  on:
    pull_request:
      branches:
        - main
      types:
        - closed
  
  jobs:
    create-release:
      if: github.event.pull_request.merged == true
      uses: obervinov/_templates/.github/workflows/release.yaml@v2.1.0
